### ISSUE TITLE
commands throw error

### ISSUE THREAD

**Issue by hacker-h** [tidalf/irbt#29]
My robot was recognized with its account:
```
$ irbt-cli.py -R
robot 0 : 520F5883DC814A9AA82CAD7B55E9D0A9
```
However all commands throw the same error:
start:
```
$ irbt-cli.py -c start
Traceback (most recent call last):
  File "/usr/local/bin/irbt-cli.py", line 4, in <module>
    __import__('pkg_resources').run_script('irbt===0.4.0.devdde6f68a', 'irbt-cli.py')
  File "/home/hacker/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/hacker/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.7/dist-packages/irbt-0.4.0.devdde6f68a-py3.7.egg/EGG-INFO/scripts/irbt-cli.py", line 96, in <module>
  File "/usr/local/lib/python3.7/dist-packages/irbt-0.4.0.devdde6f68a-py3.7.egg/irbt/robot.py", line 106, in __init__
  File "/usr/local/lib/python3.7/dist-packages/irbt-0.4.0.devdde6f68a-py3.7.egg/irbt/robot.py", line 165, in maps
IndexError: list index out of range
```

stop:
```
$ irbt-cli.py -c stop
Traceback (most recent call last):
  File "/usr/local/bin/irbt-cli.py", line 4, in <module>
    __import__('pkg_resources').run_script('irbt===0.4.0.devdde6f68a', 'irbt-cli.py')
  File "/home/hacker/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/hacker/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.7/dist-packages/irbt-0.4.0.devdde6f68a-py3.7.egg/EGG-INFO/scripts/irbt-cli.py", line 96, in <module>
  File "/usr/local/lib/python3.7/dist-packages/irbt-0.4.0.devdde6f68a-py3.7.egg/irbt/robot.py", line 106, in __init__
  File "/usr/local/lib/python3.7/dist-packages/irbt-0.4.0.devdde6f68a-py3.7.egg/irbt/robot.py", line 165, in maps
IndexError: list index out of range
```

find:
```
$ irbt-cli.py -c find
Traceback (most recent call last):
  File "/usr/local/bin/irbt-cli.py", line 4, in <module>
    __import__('pkg_resources').run_script('irbt===0.4.0.devdde6f68a', 'irbt-cli.py')
  File "/home/hacker/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/hacker/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.7/dist-packages/irbt-0.4.0.devdde6f68a-py3.7.egg/EGG-INFO/scripts/irbt-cli.py", line 96, in <module>
  File "/usr/local/lib/python3.7/dist-packages/irbt-0.4.0.devdde6f68a-py3.7.egg/irbt/robot.py", line 106, in __init__
  File "/usr/local/lib/python3.7/dist-packages/irbt-0.4.0.devdde6f68a-py3.7.egg/irbt/robot.py", line 165, in maps
IndexError: list index out of range
```

**Comment by tidalf** [comment]
What's your robot ?, I've just tested with I7
and could you try to run it with debug (-d) or some other options (like -I) thanks !

**Comment by hacker-h** [comment]
Update: My robot is apparently broken and cannot connect to the cloud anymore
